from selenium.webdriver.common.by import By

class LocatorsBasePageScooter:
    QUESTIONS_BLOCK = [By.XPATH, "//div[@class='Home_FourPart__1uthg']/div[text()='Вопросы о важном']"]
    QUESTION_1 = [By.CSS_SELECTOR, "div[id='accordion__heading-0']"]
    QUESTION_2 = [By.CSS_SELECTOR, "div[id='accordion__heading-1']"]
    QUESTION_3 = [By.CSS_SELECTOR, "div[id='accordion__heading-2']"]
    QUESTION_4 = [By.CSS_SELECTOR, "div[id='accordion__heading-3']"]
    QUESTION_5 = [By.CSS_SELECTOR, "div[id='accordion__heading-4']"]
    QUESTION_6 = [By.CSS_SELECTOR, "div[id='accordion__heading-5']"]
    QUESTION_7 = [By.CSS_SELECTOR, "div[id='accordion__heading-6']"]
    QUESTION_8 = [By.CSS_SELECTOR, "div[id='accordion__heading-7']"]
    ANSWER_1 = [By.CSS_SELECTOR, "div[id='accordion__panel-0'] p"]
    ANSWER_2 = [By.CSS_SELECTOR, "div[id='accordion__panel-1'] p"]
    ANSWER_3 = [By.CSS_SELECTOR, "div[id='accordion__panel-2'] p"]
    ANSWER_4 = [By.CSS_SELECTOR, "div[id='accordion__panel-3'] p"]
    ANSWER_5 = [By.CSS_SELECTOR, "div[id='accordion__panel-4'] p"]
    ANSWER_6 = [By.CSS_SELECTOR, "div[id='accordion__panel-5'] p"]
    ANSWER_7 = [By.CSS_SELECTOR, "div[id='accordion__panel-6'] p"]
    ANSWER_8 = [By.CSS_SELECTOR, "div[id='accordion__panel-7'] p"]
    HOW_WORK = [By.XPATH, "//div[@class='Home_ThirdPart__LSTEE']/div[text()='Как это работает']"]
    ORDER_BTN_HEADER = [By.CSS_SELECTOR, "div.Header_Nav__AGCXC button"]
    ORDER_BTN_BODY = [By.CSS_SELECTOR, "div.Home_FinishButton__1_cWm button"]
    LOGO_YANDEX = [By.CLASS_NAME, "Header_LogoYandex__3TSOI"]
    LOGO_SCOOTER = [By.CLASS_NAME, "Header_LogoScooter__3lsAR"]
    