from selenium.webdriver.common.by import By


NAME = [By.CSS_SELECTOR, "input[placeholder='* Имя']"]
SURNAME = [By.CSS_SELECTOR, "input[placeholder='* Фамилия']"]
ADDRESS = [By.CSS_SELECTOR, "input[placeholder='* Адрес: куда привезти заказ']"]
METRO = [By.CSS_SELECTOR, "input[placeholder='* Станция метро']"]
METRO_NAME_BAUMANSKAYA = [By.CSS_SELECTOR, "div.select-search__select>ul>li[data-value='60']>button"]
METRO_NAME_ELECTROZAVODSKAYA = [By.CSS_SELECTOR, "div.select-search__select>ul>li[data-value='61']>button"]
PHONE = [By.CSS_SELECTOR, "input[placeholder='* Телефон: на него позвонит курьер']"]
NEXT = [By.XPATH, "//div[@class='Order_NextButton__1_rCA']/button[text()='Далее']"]
DATE = [By.CSS_SELECTOR, "input[placeholder='* Когда привезти самокат']"]
DATEPICKER = [By.CLASS_NAME, "react-datepicker__month-container"]
DATEPICKER_DAY_1_CURRENT_MONTH = [By.XPATH, "//div[@class='react-datepicker__month']/div/div[@class='react-datepicker__day react-datepicker__day--001']"]
DATEPICKER_DAY_2_CURRENT_MONTH = [By.XPATH, "//div[@class='react-datepicker__month']/div/div[@class='react-datepicker__day react-datepicker__day--002']"]
PERIOD = [By.CSS_SELECTOR, "div.Dropdown-control"]
PERIOD_MENU_4_DAYS = [By.XPATH, "//div[@class='Dropdown-menu']/div[text()='четверо суток']"]
PERIOD_MENU_5_DAYS = [By.XPATH, "//div[@class='Dropdown-menu']/div[text()='пятеро суток']"]
COLOR_BLACK = [By.ID, "black"]
COLOR_GREY = [By.ID, "grey"]
COMMENT = [By.CSS_SELECTOR, "input[placeholder='Комментарий для курьера']"]
ORDER_BUTTON = [By.XPATH, "//div[@class='Order_Buttons__1xGrp']/button[text()='Заказать']"]
ORDER_CONFIRM = [By.XPATH, "//div[text()='Хотите оформить заказ?']"]
ORDER_CONFIRM_BUTTON = [By.XPATH, "//button[text()='Да']"]
ORDER_SUCCESS = [By.XPATH, "//div[text()='Заказ оформлен']"]
BASE_PAGE_BUTTON = [By.CSS_SELECTOR, "a.Header_LogoScooter__3lsAR"]
BUTTON_SHOW_STATUS = [By.XPATH, "//button[text()='Посмотреть статус']"]
STATUS = [By.XPATH, "//div[text()='Имя']"]
    